#! /usr/bin/env node

import inquirer from "inquirer"

// 1)Computer will generate a random number.

// 2)Ask the user to guess the number.  { DONE }

// 3)Compare users guessed number to the number which is generated by the computer and show results  {DONE}

const randomNumber = Math.floor(Math.random() * 10 +1 )

console.log("Welcom to number guessing game")

const result = await inquirer.prompt ([
    {
        name: "userGuessedNumber",
        type:"number",
        message:"Please guess a number between 1-10 : "
    }
])

if(result.userGuessedNumber === randomNumber){
    console.log("Congratulations you guessed the right number")
}
else{
    console.log("sorry, you guessed the wrong number")
}